spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.expiration=${JWT_EXPIRATION:3600000}
jwt.secret=${JWT_SECRET:CmdBDJh6KiHb1N7WUJq8bC2MDUwOT3C6}